### ISSUE TITLE
Add docs on how to generate new indexes with Star_indices pipeline

### ISSUE THREAD

**Issue by PhilPalmer** [TheJacksonLaboratory/splicing-pipelines-nf#139]
## Problem
In order to analyse the TCGA / GTEx data in the cloud, we need to have the STAR indexes for the relevant read lengths/overhangs already stored in the JAX Google Cloud account

## Solution
Upload STAR indexes, these must:
1. Be built with STAR version: 2.7.3a
2. Include all required indexes for the various read lengths/overhangs

## Implementation
The easiest thing would be to upload the STAR indexes from Sumner to GCloud @adeslatt would you be able to do this or would you be able to give access to @lmurba and @angarb and we show them how to do this?

Alternatively, we could build a mini Nextflow pipeline to do this on CloudOS, however, I think the above option is preferrable/easier because they have already been generated

**Comment by Vlad-Dembrovskyi** [comment]
Create documentation on how to generate new index

**Comment by Vlad-Dembrovskyi** [comment]
Additionally @angarb  and @cgpu to upload old and new indexes to the new GVP workspaces.

**Comment by angarb** [comment]
Here are notes from Mitch to migrate items from the cluster to cloud:
```
## add singularity to $PATH:
module load singularity

## make some convenience commands to reduce typing (note we changed container name so we can accommodate other cloud providers):
alias gcloud="singularity exec /projects/researchit/crf/containers/gcp_sdk.sif gcloud"
alias gsutil="singularity exec /projects/researchit/crf/containers/gcp_sdk.sif gsutil"

## login to gcloud; this will return a url that you need to paste into a browser, which
##   will take you through the google authentication process; you can use your jax
##   email as userid and jax password to get in. Once you authenticate, it will display
##   a code that you need to paste into the prompt provided in your ssh session on Sumner:

gcloud auth login --no-launch-browser

## see which projects you have access to:
gcloud projects list

## what is the project you are currently associated with:
gcloud config list project

## change project association:
gcloud config set project my-project

## see what buckets are associated with my-project:
gsutil ls

## see contents of a particular bucket:
gsutil ls -l gs://my-bucket

## recursively copy large directory from filesystem accessible on Sumner to your bucket:
gsutil -m -o GSUtil:parallel_composite_upload_threshold=150M cp -r my_dir gs://my_bucket/my_dir

## recursively copy a directory from your bucket to an existing directory on Sumner:
gsutil -m -o GSUtil:parallel_composite_upload_threshold=150M cp -r gs://my_bucket/my_dir my_dir
```

**Comment by angarb** [comment]
Additionally, @Vlad-Dembrovskyi has built: https://github.com/TheJacksonLaboratory/Star_indices

**Comment by angarb** [comment]
Here: https://github.com/TheJacksonLaboratory/splicing-pipelines-nf/blob/dev-v2.1/docs/Star_Index_Generation.md
