### ISSUE TITLE
CRAM files download and convertion support

### ISSUE THREAD

**Issue by sk-sahu** [TheJacksonLaboratory/splicing-pipelines-nf#205]
Adding some primary links which can help add this - 
* Biostar similar concern - https://www.biostars.org/p/371433/
* related blog - https://cemalley.com/2019/09/27/accessing-gtex-v7-v8-raw-rna-seq-data-in-the-cloud/
* related tool - https://github.com/mitre/fusera/wiki/Running-Sracp

Initial testing with Sracp fails -

Samples - `SRR8218289` and `SRR8218361` 

![image](https://user-images.githubusercontent.com/23085664/95186995-3fda2480-07e8-11eb-8ee9-e0fa53acc297.png)

Test with - 
![image](https://user-images.githubusercontent.com/23085664/95187226-8cbdfb00-07e8-11eb-8573-738f7798fbc1.png)

**Comment by Vlad-Dembrovskyi** [comment]
In new database it is not an issue anymore.
