### ISSUE TITLE
parameterize all the google life science configs 

### ISSUE THREAD

**Issue by sk-sahu** [TheJacksonLaboratory/splicing-pipelines-nf#214]
Example - #213

**Comment by Vlad-Dembrovskyi** [comment]
Change all those parameters:
https://github.com/TheJacksonLaboratory/splicing-pipelines-nf/blob/265a24330427d4661ac8f2fdbfb1ba9e1257661f/conf/executors/google.config#L3-L6

As this one:
https://github.com/TheJacksonLaboratory/splicing-pipelines-nf/blob/265a24330427d4661ac8f2fdbfb1ba9e1257661f/conf/executors/google.config#L2

**Comment by Vlad-Dembrovskyi** [comment]
Also set disc size via parameter for:
https://github.com/TheJacksonLaboratory/splicing-pipelines-nf/blob/265a24330427d4661ac8f2fdbfb1ba9e1257661f/conf/executors/google.config#L60-L62
https://github.com/TheJacksonLaboratory/splicing-pipelines-nf/blob/265a24330427d4661ac8f2fdbfb1ba9e1257661f/conf/executors/google.config#L66-L67

As in:
https://github.com/TheJacksonLaboratory/splicing-pipelines-nf/blob/265a24330427d4661ac8f2fdbfb1ba9e1257661f/conf/executors/google.config#L72
