### ISSUE TITLE
Add afterScript in the last process to remove the work/ directory

### ISSUE THREAD

**Issue by cgpu** [TheJacksonLaboratory/splicing-pipelines-nf#217]
## Problem

When running on Sumner, the `work/` will persist and leave behind TB of data that are not needed.

## Solution

```
workflow.onComplete { file('work').deleteDir() }workflow.onComplete { file('work').deleteDir() }
```

## Implementation
How will we implement the solution?
- [ ] Step 1
- [ ] Step 2
- [ ] ...

**Comment by Vlad-Dembrovskyi** [comment]
already addressed with the `--cleanup` parameter
