### ISSUE TITLE
Not to copy unnecessary files to results dir 

### ISSUE THREAD

**Issue by sk-sahu** [TheJacksonLaboratory/splicing-pipelines-nf#221]
- [x] [trimmed files - only keep logs](https://github.com/TheJacksonLaboratory/splicing-pipelines-nf/blob/master/main.nf#L484-L485)
- [x] copy `.bw` only once - all of them into the single folder
- [x] trimmed FastQCs in QC folder - all this information is available in the MultiQC
- [ ] remove the duplicated MultiQC file (keep the renamed one)
- [ ] bam files - can we figure out a way to zip this folder? Would that help with space? 
- [ ] unmapped file - making a param if a user want to generate those files. somewhere [here](https://github.com/TheJacksonLaboratory/splicing-pipelines-nf/blob/master/main.nf#L603)
- [ ] Can we zip the folders with the merged gtf [here](https://github.com/TheJacksonLaboratory/splicing-pipelines-nf/blob/master/main.nf#L686-L687)?

**Comment by Vlad-Dembrovskyi** [comment]
created separate issues for pending tasks. closing this one.
