### ISSUE TITLE
Simplify the Gen3-DRS download option

### ISSUE THREAD

**Issue by Vlad-Dembrovskyi** [TheJacksonLaboratory/splicing-pipelines-nf#287]
Currently we need to manually edit the manifest file before using it for pipeline to only include the samples of interest. We need a way to only provide samples of interest and manifest to pipeline so that pipeline edits the manifest itself. Example code following shortly.

**Comment by angarb** [comment]
Currently this is the method:

**Comment by angarb** [comment]
I would like to:

**Comment by angarb** [comment]
Alternatively, we could give the specimen id GTEX-XXXX-XXXX-XX-XXXXX and it pulls out the .bam files.

**Comment by Vlad-Dembrovskyi** [comment]
Addition:
we can save the filenames requested but not found in original manifest file into a not_found_GTEX_samples.txt file. We Should also print them as warnings to stdout.
