### ISSUE TITLE
Update gen3 documentation for new manifest file

### ISSUE THREAD

**Issue by Vlad-Dembrovskyi** [TheJacksonLaboratory/splicing-pipelines-nf#298]
After implementation of #289 and adoption of new manifest file format, I think we have to update the documentation and example files here:

https://github.com/TheJacksonLaboratory/splicing-pipelines-nf/tree/master/examples/gen3

**Comment by angarb** [comment]
Updated documentation here: 
1. https://github.com/TheJacksonLaboratory/splicing-pipelines-nf/tree/dev-v2.1/examples/GTEX
