### ISSUE TITLE
Remove network and subnetwork definition for Google Life Sciences from all configs

### ISSUE THREAD

**Issue by cgpu** [TheJacksonLaboratory/splicing-pipelines-nf#301]
## Problem
A clear and concise description of what the problem is that you would like to be solved.

## Solution
What is a possible solution to the problem?

## Implementation
How will we implement the solution?
- [ ] Step 1
- [ ] Step 2
- [ ] ...

**Comment by angarb** [comment]
@cgpu - do you know if we can do this yet?

**Comment by cgpu** [comment]
> @cgpu - do you know if we can do this yet?

Hi @angarb, yes for sure, let me make the pr and then we can test tomorrow morning to validate across the 2 CloudOS workspaces that everything is working as expected before we merge.

I will add you as a reviewer to notify you about the change, and the the branch and tag that you can use to test.

**Comment by angarb** [comment]
Thanks @cgpu !
